export const NEW_PRODUCT_DETAILS_REQUEST = "NEW_PRODUCT_DETAILS_REQUEST";
export const NEW_PRODUCT_DETAILS_SUCCESS = "NEW_PRODUCT_DETAILS_SUCCESS";
export const NEW_PRODUCT_DETAILS_UPDATE_IMAGES = "NEW_PRODUCT_DETAILS_SUCCESS";
export const NEW_PRODUCT_DETAILS_FAIL = "NEW_PRODUCT_DETAILS_FAIL";

///NO NECESITO EESTE REDUCER... CREO
export const NEW_PRODUCT_POST_REQUEST = "NEW_PRODUCT_POST_REQUEST";
export const NEW_PRODUCT_POST_SUCCESS = "NEW_PRODUCT_POST_SUCCESS";
export const NEW_PRODUCT_POST_FAILS = "NEW_PRODUCT_POST_FAILS";

///REDUCER ES PARA CAMBIAR LOS VALORES DE UN OBJETO DEL STATE

// Este tecnicamente... tampoco xd
export const NEW_PRODUCT_UPDATE_REQUEST = "NEW_PRODUCT_UPDATE_REQUEST";
export const NEW_PRODUCT_UPDATE_SUCCESS = "NEW_PRODUCT_UPDATE_SUCCESS";
export const NEW_PRODUCT_UPDATE_FAILS = "NEW_PRODUCT_UPDATE_FAILS";


export const NEW_PRODUCT_UPLOAD_IMAGE__REQUEST = "NEW_PRODUCT_UPLOAD_IMAGE__REQUEST";
export const NEW_PRODUCT_UPLOAD_IMAGE_SUCCESS = "NEW_PRODUCT_UPLOAD_IMAGE_SUCCESS";
export const NEW_PRODUCT_UPLOAD_IMAGE_FAIL = "NEW_PRODUCT_UPLOAD_IMAGE_FAIL";


export const NEW_PRODUCT_DELETE_IMAGE_REQUEST = "NEW_PRODUCT_DELETE_IMAGE_REQUEST";
export const NEW_PRODUCT_DELETE_IMAGE_SUCCESS = "NEW_PRODUCT_DELETE_IMAGE_SUCCESS";
export const NEW_PRODUCT_DELETE_IMAGE_FAIL = "NEW_PRODUCT_DELETE_IMAGE_FAIL";


export const NEW_PRODUCT_ATTRIBUTE_UPDATE = "NEW_PRODUCT_ATTRIBUTE_UPDATE";
export const NEW_PRODUCT_PLANS_UPDATE = "NEW_PRODUCT_PLANS_UPDATE";