version: "3"
services:
  fullstack:
    build: ./
    stdin_open: true
    ports: 
      - "3000:3000"
      - "5000:5000"
    environment:
      - MONGO_URL = mongodb://192.168.0.23:27017/UCAM_WEB_ECCOMERCE
  